begin;

create extension if not exists pgtap with schema extensions;

select plan(27);

select is(
  (
    select count(*)::integer
    from information_schema.columns
    where table_schema = 'public'
      and table_name in (
        'industries',
        'roles',
        'skill_categories',
        'skills',
        'skill_versions'
      )
      and column_name = 'code'
      and is_nullable = 'NO'
  ),
  5,
  'all taxonomy entities have required stable codes'
);

select is(
  (
    select count(*)::integer
    from information_schema.columns
    where table_schema = 'public'
      and table_name in (
        'industries',
        'roles',
        'skill_categories',
        'skills',
        'skill_versions'
      )
      and column_name = 'retired_at'
      and is_nullable = 'YES'
  ),
  5,
  'all taxonomy entities support non-destructive retirement'
);

select is(
  (
    select count(*)::integer
    from information_schema.columns
    where table_schema = 'public'
      and table_name in (
        'industries',
        'roles',
        'skill_categories',
        'skills',
        'skill_versions'
      )
      and column_name = 'id'
      and is_identity = 'YES'
      and identity_generation = 'BY DEFAULT'
  ),
  5,
  'taxonomy IDs are generated by default'
);

select lives_ok(
  $$insert into public.industries (name)
    values ('Taxonomy Schema Test Industry')$$,
  'industry can be inserted without explicit ID or code'
);

select lives_ok(
  $$insert into public.roles (name, description)
    values ('Taxonomy Schema Test Role', 'Database test role')$$,
  'role can be inserted without explicit ID or code'
);

select lives_ok(
  $$insert into public.skill_categories (name)
    values ('Taxonomy Schema Test Primary Category')$$,
  'primary skill category can be inserted without explicit ID or code'
);

select lives_ok(
  $$insert into public.skill_categories (name)
    values ('Taxonomy Schema Test Secondary Category')$$,
  'secondary skill category can be inserted without explicit ID or code'
);

select lives_ok(
  $$insert into public.skills (name, skill_category_id)
    select
      'Taxonomy Schema Test Skill',
      id
    from public.skill_categories
    where code = 'taxonomy-schema-test-primary-category'$$,
  'skill can be inserted without explicit ID or code'
);

select lives_ok(
  $$insert into public.skill_versions (skill_id, version, ordinal)
    select
      id,
      'Version 1.0',
      1
    from public.skills
    where code = 'taxonomy-schema-test-skill'$$,
  'skill version can omit ID, code, and release date'
);

select is(
  (
    select count(*)::integer
    from (
      select code
      from public.industries
      where code = 'taxonomy-schema-test-industry'
      union all
      select code
      from public.roles
      where code = 'taxonomy-schema-test-role'
      union all
      select code
      from public.skill_categories
      where code in (
        'taxonomy-schema-test-primary-category',
        'taxonomy-schema-test-secondary-category'
      )
      union all
      select code
      from public.skills
      where code = 'taxonomy-schema-test-skill'
      union all
      select code
      from public.skill_versions
      where code = 'version-1-0'
        and skill_id = (
          select id
          from public.skills
          where code = 'taxonomy-schema-test-skill'
        )
    ) generated_codes
  ),
  6,
  'missing taxonomy codes are generated on insert'
);

select lives_ok(
  $$update public.industries
    set name = 'Renamed Taxonomy Schema Test Industry'
    where code = 'taxonomy-schema-test-industry'$$,
  'taxonomy display name can change without changing the stable code'
);

select results_eq(
  $$select code
    from public.industries
    where name = 'Renamed Taxonomy Schema Test Industry'$$,
  array['taxonomy-schema-test-industry'::text],
  'taxonomy code remains stable after a name change'
);

select is(
  (
    select count(*)::integer
    from public.skill_category_memberships scm
    join public.skills s on s.id = scm.skill_id
    join public.skill_categories sc on sc.id = scm.skill_category_id
    where s.code = 'taxonomy-schema-test-skill'
      and sc.code = 'taxonomy-schema-test-primary-category'
  ),
  1,
  'a new skill automatically receives its primary category membership'
);

select lives_ok(
  $$update public.skills
    set skill_category_id = (
      select id
      from public.skill_categories
      where code = 'taxonomy-schema-test-secondary-category'
    )
    where code = 'taxonomy-schema-test-skill'$$,
  'primary skill category can be changed'
);

select is(
  (
    select count(*)::integer
    from public.skill_category_memberships scm
    join public.skills s on s.id = scm.skill_id
    where s.code = 'taxonomy-schema-test-skill'
  ),
  2,
  'changing the primary category preserves the previous membership and adds the new one'
);

select is(
  (
    select release_date is null
    from public.skill_versions
    where skill_id = (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
      and code = 'version-1-0'
  ),
  true,
  'skill version release date is optional'
);

select is(
  (
    select ordinal
    from public.skill_versions
    where skill_id = (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
      and code = 'version-1-0'
  ),
  1,
  'skill version ordinal remains required ordering data'
);

create function pg_temp.nonpositive_ordinal_insert_succeeds(p_skill_id bigint)
returns boolean
language plpgsql
security invoker
as $$
begin
  insert into public.skill_versions (skill_id, version, ordinal)
  values (p_skill_id, 'Invalid zero ordinal', 0);
  return true;
exception
  when check_violation then
    return false;
end;
$$;

select is(
  pg_temp.nonpositive_ordinal_insert_succeeds(
    (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
  ),
  false,
  'skill version ordinal must be positive'
);

create function pg_temp.missing_ordinal_insert_succeeds(p_skill_id bigint)
returns boolean
language plpgsql
security invoker
as $$
begin
  insert into public.skill_versions (skill_id, version)
  values (p_skill_id, 'Missing ordinal');
  return true;
exception
  when not_null_violation then
    return false;
end;
$$;

select is(
  pg_temp.missing_ordinal_insert_succeeds(
    (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
  ),
  false,
  'skill version ordinal cannot be omitted'
);

create function pg_temp.duplicate_ordinal_insert_succeeds(p_skill_id bigint)
returns boolean
language plpgsql
security invoker
as $$
begin
  insert into public.skill_versions (skill_id, version, ordinal)
  values (p_skill_id, 'Duplicate ordinal', 1);
  return true;
exception
  when unique_violation then
    return false;
end;
$$;

select is(
  pg_temp.duplicate_ordinal_insert_succeeds(
    (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
  ),
  false,
  'skill version ordinals remain unique within a skill'
);

create function pg_temp.self_relation_insert_succeeds(p_skill_id bigint)
returns boolean
language plpgsql
security invoker
as $$
begin
  insert into public.skill_relations (skill_id, related_skill_id)
  values (p_skill_id, p_skill_id);
  return true;
exception
  when check_violation then
    return false;
end;
$$;

select is(
  pg_temp.self_relation_insert_succeeds(
    (
      select id
      from public.skills
      where code = 'taxonomy-schema-test-skill'
    )
  ),
  false,
  'a skill cannot be related to itself'
);

select is(
  (
    select count(*)::integer
    from pg_constraint
    where conname in (
      'companies_industry_id_fkey',
      'job_roles_role_id_fkey',
      'skill_categories_parent_skill_category_id_fkey',
      'skills_skill_category_id_fkey',
      'tech_stacks_skill_version_id_fkey',
      'job_skill_versions_skill_version_id_fkey',
      'job_seeker_skills_skill_id_fkey',
      'job_skills_skill_id_fkey'
    )
      and confdeltype = 'r'
  ),
  8,
  'taxonomy foreign keys that protect business data use ON DELETE RESTRICT'
);

select is(
  (
    select relrowsecurity
    from pg_class
    where oid = 'public.skill_category_memberships'::regclass
  ),
  true,
  'skill category memberships have RLS enabled'
);

select policies_are(
  'public',
  'skill_category_memberships',
  array['Skill category memberships are visible to everyone.'],
  'skill category memberships expose only the read policy'
);

select ok(
  has_table_privilege(
    'authenticated',
    'public.skill_category_memberships',
    'SELECT'
  )
  and not has_table_privilege(
    'authenticated',
    'public.skill_category_memberships',
    'INSERT'
  )
  and not has_table_privilege(
    'authenticated',
    'public.skill_category_memberships',
    'UPDATE'
  )
  and not has_table_privilege(
    'authenticated',
    'public.skill_category_memberships',
    'DELETE'
  )
  and not has_table_privilege(
    'anon',
    'public.skill_category_memberships',
    'SELECT'
  ),
  'skill category membership grants are least-privilege for API roles'
);

select is(
  (
    select count(*)::integer
    from pg_constraint
    where conname in (
      'industries_code_key',
      'roles_code_key',
      'skill_categories_code_key',
      'skills_code_key',
      'skill_versions_skill_id_code_key'
    )
      and contype = 'u'
  ),
  5,
  'taxonomy codes are protected by unique constraints'
);

select lives_ok(
  $$update public.skills
    set retired_at = now()
    where code = 'taxonomy-schema-test-skill'$$,
  'taxonomy entities can be retired without deletion'
);

select * from finish();

rollback;
