/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobvanaIndexRouteImport } from './routes/jobvana.index'
import { Route as JobvanaAboutRouteImport } from './routes/jobvana.about'
import { Route as JobvanaSkillsIndexRouteImport } from './routes/jobvana.skills.index'
import { Route as JobvanaJobsIndexRouteImport } from './routes/jobvana.jobs.index'
import { Route as JobvanaCompaniesIndexRouteImport } from './routes/jobvana.companies.index'
import { Route as JobvanaJobsIdRouteImport } from './routes/jobvana.jobs.$id'
import { Route as JobvanaCompaniesIdRouteImport } from './routes/jobvana.companies.$id'
import { Route as JobvanaSkillsIdIndexRouteImport } from './routes/jobvana.skills.$id.index'
import { Route as JobvanaSkillsIdSkill_versionsSkill_version_idRouteImport } from './routes/jobvana.skills.$id.skill_versions.$skill_version_id'

const JobvanaIndexRoute = JobvanaIndexRouteImport.update({
  id: '/jobvana/',
  path: '/jobvana/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaAboutRoute = JobvanaAboutRouteImport.update({
  id: '/jobvana/about',
  path: '/jobvana/about',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaSkillsIndexRoute = JobvanaSkillsIndexRouteImport.update({
  id: '/jobvana/skills/',
  path: '/jobvana/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaJobsIndexRoute = JobvanaJobsIndexRouteImport.update({
  id: '/jobvana/jobs/',
  path: '/jobvana/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaCompaniesIndexRoute = JobvanaCompaniesIndexRouteImport.update({
  id: '/jobvana/companies/',
  path: '/jobvana/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaJobsIdRoute = JobvanaJobsIdRouteImport.update({
  id: '/jobvana/jobs/$id',
  path: '/jobvana/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaCompaniesIdRoute = JobvanaCompaniesIdRouteImport.update({
  id: '/jobvana/companies/$id',
  path: '/jobvana/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaSkillsIdIndexRoute = JobvanaSkillsIdIndexRouteImport.update({
  id: '/jobvana/skills/$id/',
  path: '/jobvana/skills/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobvanaSkillsIdSkill_versionsSkill_version_idRoute =
  JobvanaSkillsIdSkill_versionsSkill_version_idRouteImport.update({
    id: '/jobvana/skills/$id/skill_versions/$skill_version_id',
    path: '/jobvana/skills/$id/skill_versions/$skill_version_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/jobvana/about': typeof JobvanaAboutRoute
  '/jobvana': typeof JobvanaIndexRoute
  '/jobvana/companies/$id': typeof JobvanaCompaniesIdRoute
  '/jobvana/jobs/$id': typeof JobvanaJobsIdRoute
  '/jobvana/companies': typeof JobvanaCompaniesIndexRoute
  '/jobvana/jobs': typeof JobvanaJobsIndexRoute
  '/jobvana/skills': typeof JobvanaSkillsIndexRoute
  '/jobvana/skills/$id': typeof JobvanaSkillsIdIndexRoute
  '/jobvana/skills/$id/skill_versions/$skill_version_id': typeof JobvanaSkillsIdSkill_versionsSkill_version_idRoute
}
export interface FileRoutesByTo {
  '/jobvana/about': typeof JobvanaAboutRoute
  '/jobvana': typeof JobvanaIndexRoute
  '/jobvana/companies/$id': typeof JobvanaCompaniesIdRoute
  '/jobvana/jobs/$id': typeof JobvanaJobsIdRoute
  '/jobvana/companies': typeof JobvanaCompaniesIndexRoute
  '/jobvana/jobs': typeof JobvanaJobsIndexRoute
  '/jobvana/skills': typeof JobvanaSkillsIndexRoute
  '/jobvana/skills/$id': typeof JobvanaSkillsIdIndexRoute
  '/jobvana/skills/$id/skill_versions/$skill_version_id': typeof JobvanaSkillsIdSkill_versionsSkill_version_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/jobvana/about': typeof JobvanaAboutRoute
  '/jobvana/': typeof JobvanaIndexRoute
  '/jobvana/companies/$id': typeof JobvanaCompaniesIdRoute
  '/jobvana/jobs/$id': typeof JobvanaJobsIdRoute
  '/jobvana/companies/': typeof JobvanaCompaniesIndexRoute
  '/jobvana/jobs/': typeof JobvanaJobsIndexRoute
  '/jobvana/skills/': typeof JobvanaSkillsIndexRoute
  '/jobvana/skills/$id/': typeof JobvanaSkillsIdIndexRoute
  '/jobvana/skills/$id/skill_versions/$skill_version_id': typeof JobvanaSkillsIdSkill_versionsSkill_version_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/jobvana/about'
    | '/jobvana'
    | '/jobvana/companies/$id'
    | '/jobvana/jobs/$id'
    | '/jobvana/companies'
    | '/jobvana/jobs'
    | '/jobvana/skills'
    | '/jobvana/skills/$id'
    | '/jobvana/skills/$id/skill_versions/$skill_version_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/jobvana/about'
    | '/jobvana'
    | '/jobvana/companies/$id'
    | '/jobvana/jobs/$id'
    | '/jobvana/companies'
    | '/jobvana/jobs'
    | '/jobvana/skills'
    | '/jobvana/skills/$id'
    | '/jobvana/skills/$id/skill_versions/$skill_version_id'
  id:
    | '__root__'
    | '/jobvana/about'
    | '/jobvana/'
    | '/jobvana/companies/$id'
    | '/jobvana/jobs/$id'
    | '/jobvana/companies/'
    | '/jobvana/jobs/'
    | '/jobvana/skills/'
    | '/jobvana/skills/$id/'
    | '/jobvana/skills/$id/skill_versions/$skill_version_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  JobvanaAboutRoute: typeof JobvanaAboutRoute
  JobvanaIndexRoute: typeof JobvanaIndexRoute
  JobvanaCompaniesIdRoute: typeof JobvanaCompaniesIdRoute
  JobvanaJobsIdRoute: typeof JobvanaJobsIdRoute
  JobvanaCompaniesIndexRoute: typeof JobvanaCompaniesIndexRoute
  JobvanaJobsIndexRoute: typeof JobvanaJobsIndexRoute
  JobvanaSkillsIndexRoute: typeof JobvanaSkillsIndexRoute
  JobvanaSkillsIdIndexRoute: typeof JobvanaSkillsIdIndexRoute
  JobvanaSkillsIdSkill_versionsSkill_version_idRoute: typeof JobvanaSkillsIdSkill_versionsSkill_version_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobvana/': {
      id: '/jobvana/'
      path: '/jobvana'
      fullPath: '/jobvana'
      preLoaderRoute: typeof JobvanaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/about': {
      id: '/jobvana/about'
      path: '/jobvana/about'
      fullPath: '/jobvana/about'
      preLoaderRoute: typeof JobvanaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/skills/': {
      id: '/jobvana/skills/'
      path: '/jobvana/skills'
      fullPath: '/jobvana/skills'
      preLoaderRoute: typeof JobvanaSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/jobs/': {
      id: '/jobvana/jobs/'
      path: '/jobvana/jobs'
      fullPath: '/jobvana/jobs'
      preLoaderRoute: typeof JobvanaJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/companies/': {
      id: '/jobvana/companies/'
      path: '/jobvana/companies'
      fullPath: '/jobvana/companies'
      preLoaderRoute: typeof JobvanaCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/jobs/$id': {
      id: '/jobvana/jobs/$id'
      path: '/jobvana/jobs/$id'
      fullPath: '/jobvana/jobs/$id'
      preLoaderRoute: typeof JobvanaJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/companies/$id': {
      id: '/jobvana/companies/$id'
      path: '/jobvana/companies/$id'
      fullPath: '/jobvana/companies/$id'
      preLoaderRoute: typeof JobvanaCompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/skills/$id/': {
      id: '/jobvana/skills/$id/'
      path: '/jobvana/skills/$id'
      fullPath: '/jobvana/skills/$id'
      preLoaderRoute: typeof JobvanaSkillsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobvana/skills/$id/skill_versions/$skill_version_id': {
      id: '/jobvana/skills/$id/skill_versions/$skill_version_id'
      path: '/jobvana/skills/$id/skill_versions/$skill_version_id'
      fullPath: '/jobvana/skills/$id/skill_versions/$skill_version_id'
      preLoaderRoute: typeof JobvanaSkillsIdSkill_versionsSkill_version_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  JobvanaAboutRoute: JobvanaAboutRoute,
  JobvanaIndexRoute: JobvanaIndexRoute,
  JobvanaCompaniesIdRoute: JobvanaCompaniesIdRoute,
  JobvanaJobsIdRoute: JobvanaJobsIdRoute,
  JobvanaCompaniesIndexRoute: JobvanaCompaniesIndexRoute,
  JobvanaJobsIndexRoute: JobvanaJobsIndexRoute,
  JobvanaSkillsIndexRoute: JobvanaSkillsIndexRoute,
  JobvanaSkillsIdIndexRoute: JobvanaSkillsIdIndexRoute,
  JobvanaSkillsIdSkill_versionsSkill_version_idRoute:
    JobvanaSkillsIdSkill_versionsSkill_version_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
