


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "gis";


ALTER SCHEMA "gis" OWNER TO "postgres";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE SCHEMA IF NOT EXISTS "test";


ALTER SCHEMA "test" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "postgis" WITH SCHEMA "gis";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."address_type" AS ENUM (
    'headquarters',
    'office'
);


ALTER TYPE "public"."address_type" OWNER TO "postgres";


CREATE TYPE "public"."application_status" AS ENUM (
    'submitted',
    'accepted',
    'declined',
    'withdrawn'
);


ALTER TYPE "public"."application_status" OWNER TO "postgres";


CREATE TYPE "public"."company_application_notification" AS ENUM (
    'submitted',
    'withdrawn',
    'round_accepted',
    'round_declined'
);


ALTER TYPE "public"."company_application_notification" OWNER TO "postgres";


CREATE TYPE "public"."interview_round_status" AS ENUM (
    'pending',
    'accepted',
    'declined'
);


ALTER TYPE "public"."interview_round_status" OWNER TO "postgres";


CREATE TYPE "public"."job_salary_type" AS ENUM (
    'annual',
    'hourly'
);


ALTER TYPE "public"."job_salary_type" OWNER TO "postgres";


CREATE TYPE "public"."job_seeker_application_notification" AS ENUM (
    'accepted',
    'declined',
    'round_accepted',
    'round_declined'
);


ALTER TYPE "public"."job_seeker_application_notification" OWNER TO "postgres";


CREATE TYPE "public"."job_status" AS ENUM (
    'open',
    'filled',
    'closed',
    'draft'
);


ALTER TYPE "public"."job_status" OWNER TO "postgres";


CREATE TYPE "public"."job_type" AS ENUM (
    'full_time',
    'part_time',
    'contract',
    'internship'
);


ALTER TYPE "public"."job_type" OWNER TO "postgres";


CREATE TYPE "public"."notification_status" AS ENUM (
    'unread',
    'read',
    'archived'
);


ALTER TYPE "public"."notification_status" OWNER TO "postgres";


CREATE TYPE "public"."user_type" AS ENUM (
    'company',
    'job_seeker'
);


ALTER TYPE "public"."user_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_company"("_user_id" "uuid") RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
SET search_path = public, pg_temp;
SELECT EXISTS (
  SELECT 1
  FROM public.companies c
  WHERE c.user_id = _user_id
);
$$;


ALTER FUNCTION "public"."is_company"("_user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_job_seeker"("_user_id" "uuid") RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
SELECT EXISTS (
  SELECT 1
  FROM public.job_seekers js
  WHERE js.user_id = _user_id
);
$$;


ALTER FUNCTION "public"."is_job_seeker"("_user_id" "uuid") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."company_addresses" (
    "id" bigint NOT NULL,
    "street" "text" NOT NULL,
    "city" "text" NOT NULL,
    "state" "text" NOT NULL,
    "zip" "text" NOT NULL,
    "company_id" bigint NOT NULL,
    "type" "public"."address_type" NOT NULL,
    "street_2" "text",
    "phone" "text",
    "location" "gis"."geography"
);


ALTER TABLE "public"."company_addresses" OWNER TO "postgres";


ALTER TABLE "public"."company_addresses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."addresses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."application_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "application_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "event" "public"."application_status" NOT NULL
);


ALTER TABLE "public"."application_events" OWNER TO "postgres";


ALTER TABLE "public"."application_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."application_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."application_resumes" (
    "application_id" bigint NOT NULL,
    "resume_path" "text" NOT NULL
);


ALTER TABLE "public"."application_resumes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."applications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_id" bigint NOT NULL,
    "reason" "text",
    "job_seeker_id" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "status" "public"."application_status" DEFAULT 'submitted'::"public"."application_status" NOT NULL
);


ALTER TABLE "public"."applications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."companies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "num_employees" integer NOT NULL,
    "industry_id" bigint NOT NULL,
    "description" "text" NOT NULL,
    "user_id" "uuid",
    "contact_email" "text",
    "interview_process" "jsonb"
);


ALTER TABLE "public"."companies" OWNER TO "postgres";


ALTER TABLE "public"."companies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."companies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company_application_notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "application_id" bigint NOT NULL,
    "interview_round_id" bigint,
    "type" "public"."company_application_notification" NOT NULL,
    "status" "public"."notification_status" DEFAULT 'unread'::"public"."notification_status" NOT NULL
);


ALTER TABLE "public"."company_application_notifications" OWNER TO "postgres";


ALTER TABLE "public"."company_application_notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."company_application_notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."company_tech_stacks" (
    "company_id" bigint NOT NULL,
    "skill_version_id" bigint NOT NULL
);


ALTER TABLE "public"."company_tech_stacks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hidden_jobs" (
    "job_seeker_id" bigint NOT NULL,
    "job_id" bigint NOT NULL,
    "is_permanent" boolean
);


ALTER TABLE "public"."hidden_jobs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."industries" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."industries" OWNER TO "postgres";


ALTER TABLE "public"."industries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."industries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."interview_round_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "interview_round_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "event" "public"."interview_round_status" NOT NULL
);


ALTER TABLE "public"."interview_round_events" OWNER TO "postgres";


ALTER TABLE "public"."interview_round_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."interview_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."interview_rounds" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "interview_id" bigint NOT NULL,
    "round" integer NOT NULL,
    "job_seeker_response" "public"."interview_round_status" DEFAULT 'pending'::"public"."interview_round_status" NOT NULL,
    "company_response" "public"."interview_round_status" DEFAULT 'pending'::"public"."interview_round_status" NOT NULL,
    CONSTRAINT "interview_rounds_round_check" CHECK ((("round" >= 1) AND ("round" <= 5)))
);


ALTER TABLE "public"."interview_rounds" OWNER TO "postgres";


ALTER TABLE "public"."interview_rounds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."interview_rounds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."interviews" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "application_id" bigint NOT NULL
);


ALTER TABLE "public"."interviews" OWNER TO "postgres";


ALTER TABLE "public"."interviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."interviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."applications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_applications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_roles" (
    "job_id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    "percent" integer NOT NULL,
    "role_level" integer NOT NULL,
    CONSTRAINT "job_roles_percent_check" CHECK ((("percent" >= 1) AND ("percent" <= 100))),
    CONSTRAINT "job_roles_role_level_check" CHECK ((("role_level" >= 0) AND ("role_level" <= 4)))
);


ALTER TABLE "public"."job_roles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_seeker_application_notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "application_id" bigint NOT NULL,
    "interview_round_id" bigint,
    "type" "public"."job_seeker_application_notification" NOT NULL,
    "status" "public"."notification_status" DEFAULT 'unread'::"public"."notification_status" NOT NULL
);


ALTER TABLE "public"."job_seeker_application_notifications" OWNER TO "postgres";


ALTER TABLE "public"."job_seeker_application_notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_seeker_application_notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_seeker_saved_searches" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "job_seeker_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "search_filters" "jsonb" NOT NULL
);


ALTER TABLE "public"."job_seeker_saved_searches" OWNER TO "postgres";


ALTER TABLE "public"."job_seeker_saved_searches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_seeker_saved_searches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_seeker_skills" (
    "job_seeker_id" bigint NOT NULL,
    "skill_id" bigint NOT NULL
);


ALTER TABLE "public"."job_seeker_skills" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_seekers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "active_resume_id" "uuid"
);


ALTER TABLE "public"."job_seekers" OWNER TO "postgres";


ALTER TABLE "public"."job_seekers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job_seekers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."job_skill_versions" (
    "job_id" bigint NOT NULL,
    "skill_version_id" bigint NOT NULL
);


ALTER TABLE "public"."job_skill_versions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."job_skills" (
    "job_id" bigint NOT NULL,
    "skill_id" bigint NOT NULL
);


ALTER TABLE "public"."job_skills" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "status" "public"."job_status" DEFAULT 'open'::"public"."job_status" NOT NULL,
    "description" "text",
    "salary_low" bigint NOT NULL,
    "salary_high" bigint NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "public"."job_type" DEFAULT 'full_time'::"public"."job_type" NOT NULL,
    "salary_type" "public"."job_salary_type" DEFAULT 'annual'::"public"."job_salary_type" NOT NULL,
    "company_address_id" bigint,
    "interview_process" "jsonb",
    CONSTRAINT "salary_check" CHECK ((("salary_low")::integer <= ("salary_high")::integer)),
    CONSTRAINT "salary_check_type" CHECK (((("salary_type" = 'annual'::"public"."job_salary_type") AND ("salary_low" >= 10000) AND ("salary_high" <= 200000)) OR (("salary_type" = 'hourly'::"public"."job_salary_type") AND ("salary_low" >= 20) AND ("salary_high" <= 200))))
);


ALTER TABLE "public"."jobs" OWNER TO "postgres";


ALTER TABLE "public"."jobs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."jobs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "reference" "text"
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."saved_jobs" (
    "job_seeker_id" bigint NOT NULL,
    "job_id" bigint NOT NULL
);


ALTER TABLE "public"."saved_jobs" OWNER TO "postgres";


COMMENT ON TABLE "public"."saved_jobs" IS 'This is a duplicate of hidden_jobs';



CREATE TABLE IF NOT EXISTS "public"."skill_categories" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "parent_skill_category_id" bigint,
    "description" "text",
    "reference" "text",
    "notes" "text"
);


ALTER TABLE "public"."skill_categories" OWNER TO "postgres";


ALTER TABLE "public"."skill_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."skill_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."skill_relations" (
    "skill_id" bigint NOT NULL,
    "related_skill_id" bigint NOT NULL,
    "is_bidirectional" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."skill_relations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."skill_versions" (
    "id" bigint NOT NULL,
    "skill_id" bigint NOT NULL,
    "version" "text" NOT NULL,
    "reference" "text",
    "notes" "text",
    "release_date" "date" NOT NULL,
    "ordinal" integer NOT NULL
);


ALTER TABLE "public"."skill_versions" OWNER TO "postgres";


ALTER TABLE "public"."skill_versions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."skill_versions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."skills" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "skill_category_id" bigint NOT NULL,
    "abbreviation" "text",
    "reference" "text",
    "notes" "text"
);


ALTER TABLE "public"."skills" OWNER TO "postgres";


ALTER TABLE "public"."skills" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."skills_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."titles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_registrations" (
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_type" "public"."user_type" NOT NULL
);


ALTER TABLE "public"."user_registrations" OWNER TO "postgres";


ALTER TABLE ONLY "public"."company_addresses"
    ADD CONSTRAINT "addresses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."application_events"
    ADD CONSTRAINT "application_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."application_resumes"
    ADD CONSTRAINT "application_resumes_pkey" PRIMARY KEY ("application_id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."company_application_notifications"
    ADD CONSTRAINT "company_application_notifications_application_id_interview_roun" UNIQUE ("application_id", "interview_round_id", "type");



ALTER TABLE ONLY "public"."company_application_notifications"
    ADD CONSTRAINT "company_application_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hidden_jobs"
    ADD CONSTRAINT "hidden_jobs_pkey" PRIMARY KEY ("job_seeker_id", "job_id");



ALTER TABLE ONLY "public"."industries"
    ADD CONSTRAINT "industries_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."industries"
    ADD CONSTRAINT "industries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."interview_round_events"
    ADD CONSTRAINT "interview_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."interview_rounds"
    ADD CONSTRAINT "interview_rounds_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."interviews"
    ADD CONSTRAINT "interviews_application_id_key" UNIQUE ("application_id");



ALTER TABLE ONLY "public"."interviews"
    ADD CONSTRAINT "interviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "job_applications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_roles"
    ADD CONSTRAINT "job_roles_pkey" PRIMARY KEY ("job_id", "role_id");



ALTER TABLE ONLY "public"."job_seeker_application_notifications"
    ADD CONSTRAINT "job_seeker_application_notifications_application_id_intervew_ro" UNIQUE ("application_id", "interview_round_id", "type");



ALTER TABLE ONLY "public"."job_seeker_application_notifications"
    ADD CONSTRAINT "job_seeker_application_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "job_seeker_id_job_id" UNIQUE ("job_seeker_id", "job_id");



ALTER TABLE ONLY "public"."job_seeker_saved_searches"
    ADD CONSTRAINT "job_seeker_saved_searches_job_seeker_id_name" UNIQUE ("job_seeker_id", "name");



ALTER TABLE ONLY "public"."job_seeker_saved_searches"
    ADD CONSTRAINT "job_seeker_saved_searches_job_seeker_id_search_filters" UNIQUE ("job_seeker_id", "search_filters");



ALTER TABLE ONLY "public"."job_seeker_saved_searches"
    ADD CONSTRAINT "job_seeker_saved_searches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_seeker_skills"
    ADD CONSTRAINT "job_seeker_skills_pkey" PRIMARY KEY ("job_seeker_id", "skill_id");



ALTER TABLE ONLY "public"."job_seekers"
    ADD CONSTRAINT "job_seekers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."job_seekers"
    ADD CONSTRAINT "job_seekers_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."job_skill_versions"
    ADD CONSTRAINT "job_skill_versions_pkey" PRIMARY KEY ("job_id", "skill_version_id");



ALTER TABLE ONLY "public"."job_skills"
    ADD CONSTRAINT "job_skills_pkey" PRIMARY KEY ("job_id", "skill_id");



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs2_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saved_jobs"
    ADD CONSTRAINT "saved_jobs_pkey" PRIMARY KEY ("job_seeker_id", "job_id");



ALTER TABLE ONLY "public"."skill_relations"
    ADD CONSTRAINT "skill_relations_pkey" PRIMARY KEY ("skill_id", "related_skill_id");



ALTER TABLE ONLY "public"."skill_categories"
    ADD CONSTRAINT "skill_types_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."skill_versions"
    ADD CONSTRAINT "skill_versions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."skills"
    ADD CONSTRAINT "skills_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."company_tech_stacks"
    ADD CONSTRAINT "tech_stacks_pkey" PRIMARY KEY ("company_id", "skill_version_id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "titles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "titles_title_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."user_registrations"
    ADD CONSTRAINT "user_registrations_pkey" PRIMARY KEY ("user_id");



CREATE INDEX "application_events_application_id_idx" ON "public"."application_events" USING "btree" ("application_id");



CREATE INDEX "application_events_user_id_idx" ON "public"."application_events" USING "btree" ("user_id");



CREATE INDEX "applications_job_id_idx" ON "public"."applications" USING "btree" ("job_id");



CREATE INDEX "companies_industry_id_idx" ON "public"."companies" USING "btree" ("industry_id");



CREATE INDEX "company_addresses_geo_index" ON "public"."company_addresses" USING "gist" ("location");



CREATE INDEX "company_tech_stacks_skill_version_id_idx" ON "public"."company_tech_stacks" USING "btree" ("skill_version_id");



CREATE UNIQUE INDEX "interview_round" ON "public"."interview_rounds" USING "btree" ("interview_id", "round");



CREATE INDEX "job_roles_role_id_idx" ON "public"."job_roles" USING "btree" ("role_id");



CREATE INDEX "job_seeker_skills_skill_id_idx" ON "public"."job_seeker_skills" USING "btree" ("skill_id");



CREATE INDEX "job_seekers_active_resume_id_idx" ON "public"."job_seekers" USING "btree" ("active_resume_id");



CREATE UNIQUE INDEX "job_skill" ON "public"."job_skills" USING "btree" ("job_id", "skill_id");



CREATE UNIQUE INDEX "job_skill_version" ON "public"."job_skill_versions" USING "btree" ("job_id", "skill_version_id");



CREATE INDEX "job_skill_versions_skill_version_id_idx" ON "public"."job_skill_versions" USING "btree" ("skill_version_id");



CREATE INDEX "job_skills_skill_id_idx" ON "public"."job_skills" USING "btree" ("skill_id");



CREATE INDEX "jobs_company_address_id_idx" ON "public"."jobs" USING "btree" ("company_address_id");



CREATE INDEX "jobs_company_id_idx" ON "public"."jobs" USING "btree" ("company_id");



CREATE INDEX "skill_categories_parent_skill_category_id_idx" ON "public"."skill_categories" USING "btree" ("parent_skill_category_id");



CREATE INDEX "skill_relations_related_skill_id_idx" ON "public"."skill_relations" USING "btree" ("related_skill_id");



CREATE UNIQUE INDEX "skill_version_ordinal" ON "public"."skill_versions" USING "btree" ("skill_id", "ordinal");



CREATE INDEX "skills_skill_category_id_idx" ON "public"."skills" USING "btree" ("skill_category_id");



CREATE UNIQUE INDEX "unique_headquarters" ON "public"."company_addresses" USING "btree" ("company_id", "type") WHERE ("type" = 'headquarters'::"public"."address_type");



ALTER TABLE ONLY "public"."company_addresses"
    ADD CONSTRAINT "addresses_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."application_events"
    ADD CONSTRAINT "application_events_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."application_events"
    ADD CONSTRAINT "application_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."application_resumes"
    ADD CONSTRAINT "application_resumes_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."applications"
    ADD CONSTRAINT "applications_job_seeker_id_fkey" FOREIGN KEY ("job_seeker_id") REFERENCES "public"."job_seekers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_industry_id_fkey" FOREIGN KEY ("industry_id") REFERENCES "public"."industries"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."company_application_notifications"
    ADD CONSTRAINT "company_application_notifications_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."company_application_notifications"
    ADD CONSTRAINT "company_application_notifications_interview_round_id_fkey" FOREIGN KEY ("interview_round_id") REFERENCES "public"."interview_rounds"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hidden_jobs"
    ADD CONSTRAINT "hidden_jobs_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."hidden_jobs"
    ADD CONSTRAINT "hidden_jobs_job_seeker_id_fkey" FOREIGN KEY ("job_seeker_id") REFERENCES "public"."job_seekers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."interview_round_events"
    ADD CONSTRAINT "interview_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."interview_round_events"
    ADD CONSTRAINT "interview_round_events_interview_round_id_fkey" FOREIGN KEY ("interview_round_id") REFERENCES "public"."interview_rounds"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."interview_rounds"
    ADD CONSTRAINT "interview_rounds_interview_id_fkey" FOREIGN KEY ("interview_id") REFERENCES "public"."interviews"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."interviews"
    ADD CONSTRAINT "interviews_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_roles"
    ADD CONSTRAINT "job_roles_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_roles"
    ADD CONSTRAINT "job_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seeker_application_notifications"
    ADD CONSTRAINT "job_seeker_application_notifications_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seeker_application_notifications"
    ADD CONSTRAINT "job_seeker_application_notifications_interview_round_id_fkey" FOREIGN KEY ("interview_round_id") REFERENCES "public"."interview_rounds"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seeker_saved_searches"
    ADD CONSTRAINT "job_seeker_saved_searches_job_seeker_id_fkey" FOREIGN KEY ("job_seeker_id") REFERENCES "public"."job_seekers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seeker_skills"
    ADD CONSTRAINT "job_seeker_skills_job_seeker_id_fkey" FOREIGN KEY ("job_seeker_id") REFERENCES "public"."job_seekers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seeker_skills"
    ADD CONSTRAINT "job_seeker_skills_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_seekers"
    ADD CONSTRAINT "job_seekers_active_resume_id_fkey" FOREIGN KEY ("active_resume_id") REFERENCES "storage"."objects"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."job_seekers"
    ADD CONSTRAINT "job_seekers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_skill_versions"
    ADD CONSTRAINT "job_skill_versions_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_skill_versions"
    ADD CONSTRAINT "job_skill_versions_skill_version_id_fkey" FOREIGN KEY ("skill_version_id") REFERENCES "public"."skill_versions"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_skills"
    ADD CONSTRAINT "job_skills_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."job_skills"
    ADD CONSTRAINT "job_skills_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."jobs"
    ADD CONSTRAINT "jobs_location_fkey" FOREIGN KEY ("company_address_id") REFERENCES "public"."company_addresses"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."saved_jobs"
    ADD CONSTRAINT "saved_jobs_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saved_jobs"
    ADD CONSTRAINT "saved_jobs_job_seeker_id_fkey" FOREIGN KEY ("job_seeker_id") REFERENCES "public"."job_seekers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skill_categories"
    ADD CONSTRAINT "skill_categories_parent_skill_category_id_fkey" FOREIGN KEY ("parent_skill_category_id") REFERENCES "public"."skill_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skill_relations"
    ADD CONSTRAINT "skill_relations_related_skill_id_fkey" FOREIGN KEY ("related_skill_id") REFERENCES "public"."skills"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skill_relations"
    ADD CONSTRAINT "skill_relations_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skill_versions"
    ADD CONSTRAINT "skill_versions_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."skills"
    ADD CONSTRAINT "skills_skill_category_id_fkey" FOREIGN KEY ("skill_category_id") REFERENCES "public"."skill_categories"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."company_tech_stacks"
    ADD CONSTRAINT "tech_stacks_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."company_tech_stacks"
    ADD CONSTRAINT "tech_stacks_skill_version_id_fkey" FOREIGN KEY ("skill_version_id") REFERENCES "public"."skill_versions"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_registrations"
    ADD CONSTRAINT "user_registrations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Addresses are visible to everyone." ON "public"."company_addresses" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Addresses can only be added by their companies" ON "public"."company_addresses" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "company_addresses"."company_id"))));



CREATE POLICY "Addresses can only be deleted by their companies" ON "public"."company_addresses" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "company_addresses"."company_id"))));



CREATE POLICY "Addresses can only be updated by their companies" ON "public"."company_addresses" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "company_addresses"."company_id"))));



CREATE POLICY "Companies and job seekers can create rounds" ON "public"."interview_rounds" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                   FROM "public"."interviews"
                  WHERE ("interviews"."id" = "interview_rounds"."interview_id"))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                           FROM "public"."interviews"
                          WHERE ("interviews"."id" = "interview_rounds"."interview_id")))))))))));



CREATE POLICY "Companies and job seekers can update applications" ON "public"."applications" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "applications"."job_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "applications"."job_seeker_id")))));



CREATE POLICY "Companies and job seekers can update rounds" ON "public"."interview_rounds" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                   FROM "public"."interviews"
                  WHERE ("interviews"."id" = "interview_rounds"."interview_id"))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                           FROM "public"."interviews"
                          WHERE ("interviews"."id" = "interview_rounds"."interview_id")))))))))));



CREATE POLICY "Companies and job seekers can view applications" ON "public"."applications" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "applications"."job_id"))))) OR "public"."is_job_seeker"("auth"."uid"())));



CREATE POLICY "Companies and job seekers can view job skills" ON "public"."job_skills" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_skills"."job_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"))));



CREATE POLICY "Companies and job seekers can view resumes for their job applic" ON "public"."application_resumes" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "application_resumes"."application_id"))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "application_resumes"."application_id")))))));



CREATE POLICY "Companies are visible to themselves or to job seekers" ON "public"."companies" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR "public"."is_job_seeker"("auth"."uid"())));



CREATE POLICY "Companies can add job skills" ON "public"."job_skills" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_skills"."job_id"))))));



CREATE POLICY "Companies can create notifications" ON "public"."job_seeker_application_notifications" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "job_seeker_application_notifications"."application_id"))))))));



CREATE POLICY "Companies can delete job skills" ON "public"."job_skills" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_skills"."job_id"))))));



CREATE POLICY "Companies can edit their own data" ON "public"."companies" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Companies can read their notifications" ON "public"."company_application_notifications" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "company_application_notifications"."application_id"))))))));



CREATE POLICY "Companies can start interviews" ON "public"."interviews" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "interviews"."application_id"))))))));



CREATE POLICY "Companies can update job skills" ON "public"."job_skills" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_skills"."job_id"))))));



CREATE POLICY "Companies can update their notifications" ON "public"."company_application_notifications" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "company_application_notifications"."application_id"))))))));



CREATE POLICY "Enable insert for authenticated users of type company only" ON "public"."companies" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") AND (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "user_registrations"."user_id"
   FROM "public"."user_registrations"
  WHERE ("user_registrations"."user_type" = 'company'::"public"."user_type")))));



CREATE POLICY "Enable insert for authenticated users of type job seeker only" ON "public"."job_seekers" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") AND (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "user_registrations"."user_id"
   FROM "public"."user_registrations"
  WHERE ("user_registrations"."user_type" = 'job_seeker'::"public"."user_type")))));



CREATE POLICY "Enable read access for all users" ON "public"."industries" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Job interview rounds are visible to job seekers and companies" ON "public"."interview_rounds" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                   FROM "public"."interviews"
                  WHERE ("interviews"."id" = "interview_rounds"."interview_id"))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                           FROM "public"."interviews"
                          WHERE ("interviews"."id" = "interview_rounds"."interview_id")))))))))));



CREATE POLICY "Job interviews are visible to job seekers and companies" ON "public"."interviews" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "interviews"."application_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "interviews"."application_id")))))))));



CREATE POLICY "Job roles are creatable by their companies" ON "public"."job_roles" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_roles"."job_id"))))));



CREATE POLICY "Job roles are deletable by their companies" ON "public"."job_roles" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_roles"."job_id"))))));



CREATE POLICY "Job roles are editable by their companies" ON "public"."job_roles" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_roles"."job_id"))))));



CREATE POLICY "Job roles are visible to their companies or to job seekers" ON "public"."job_roles" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" = "job_roles"."job_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"))));



CREATE POLICY "Job seekers and companies can create application events" ON "public"."application_events" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "application_events"."application_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "application_events"."application_id")))))))));



CREATE POLICY "Job seekers and companies can create interview events" ON "public"."interview_round_events" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                   FROM "public"."interviews"
                  WHERE ("interviews"."id" IN ( SELECT "interview_rounds"."interview_id"
                           FROM "public"."interview_rounds"
                          WHERE ("interview_rounds"."id" = "interview_round_events"."interview_round_id"))))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                           FROM "public"."interviews"
                          WHERE ("interviews"."id" IN ( SELECT "interview_rounds"."interview_id"
                                   FROM "public"."interview_rounds"
                                  WHERE ("interview_rounds"."id" = "interview_round_events"."interview_round_id")))))))))))));



CREATE POLICY "Job seekers and companies can view their application events" ON "public"."application_events" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "application_events"."application_id"))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" = "application_events"."application_id")))))))));



CREATE POLICY "Job seekers and companies can view their interview events" ON "public"."interview_round_events" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                   FROM "public"."interviews"
                  WHERE ("interviews"."id" IN ( SELECT "interview_rounds"."interview_id"
                           FROM "public"."interview_rounds"
                          WHERE ("interview_rounds"."id" = "interview_round_events"."interview_round_id"))))))))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" IN ( SELECT "jobs"."company_id"
           FROM "public"."jobs"
          WHERE ("jobs"."id" IN ( SELECT "applications"."job_id"
                   FROM "public"."applications"
                  WHERE ("applications"."id" IN ( SELECT "interviews"."application_id"
                           FROM "public"."interviews"
                          WHERE ("interviews"."id" IN ( SELECT "interview_rounds"."interview_id"
                                   FROM "public"."interview_rounds"
                                  WHERE ("interview_rounds"."id" = "interview_round_events"."interview_round_id")))))))))))));



CREATE POLICY "Job seekers are visible to themselves or to companies" ON "public"."job_seekers" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR "public"."is_company"("auth"."uid"())));



CREATE POLICY "Job seekers can apply for jobs" ON "public"."applications" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "applications"."job_seeker_id"))));



CREATE POLICY "Job seekers can create application resumes" ON "public"."application_resumes" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "application_resumes"."application_id"))))));



CREATE POLICY "Job seekers can create notifications" ON "public"."company_application_notifications" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "company_application_notifications"."application_id"))))));



CREATE POLICY "Job seekers can edit their own data" ON "public"."job_seekers" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Job seekers can manage hidden jobs" ON "public"."hidden_jobs" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "hidden_jobs"."job_seeker_id"))));



CREATE POLICY "Job seekers can manage their saved searches" ON "public"."job_seeker_saved_searches" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "job_seeker_saved_searches"."job_seeker_id"))));



CREATE POLICY "Job seekers can manage their skills" ON "public"."job_seeker_skills" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "job_seeker_skills"."job_seeker_id"))));



CREATE POLICY "Job seekers can read their notificaitons" ON "public"."job_seeker_application_notifications" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "job_seeker_application_notifications"."application_id"))))));



CREATE POLICY "Job seekers can save jobs" ON "public"."saved_jobs" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "saved_jobs"."job_seeker_id"))));



CREATE POLICY "Job seekers can unsave jobs" ON "public"."saved_jobs" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "saved_jobs"."job_seeker_id"))));



CREATE POLICY "Job seekers can update their notifications" ON "public"."job_seeker_application_notifications" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" IN ( SELECT "applications"."job_seeker_id"
           FROM "public"."applications"
          WHERE ("applications"."id" = "job_seeker_application_notifications"."application_id"))))));



CREATE POLICY "Job seekers can view their saved jobs" ON "public"."saved_jobs" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"
  WHERE ("job_seekers"."id" = "saved_jobs"."job_seeker_id"))));



CREATE POLICY "Job skill versions are visible to everyone." ON "public"."job_skill_versions" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Jobs are creatable by their companies" ON "public"."jobs" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "jobs"."company_id"))));



CREATE POLICY "Jobs are deletable by their companies" ON "public"."jobs" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "jobs"."company_id"))));



CREATE POLICY "Jobs are editable by their companies" ON "public"."jobs" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "jobs"."company_id"))));



CREATE POLICY "Jobs are visible to their companies or to job seekers" ON "public"."jobs" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") IN ( SELECT "companies"."user_id"
   FROM "public"."companies"
  WHERE ("companies"."id" = "jobs"."company_id"))) OR (( SELECT "auth"."uid"() AS "uid") IN ( SELECT "job_seekers"."user_id"
   FROM "public"."job_seekers"))));



CREATE POLICY "New users can register" ON "public"."user_registrations" FOR INSERT WITH CHECK (true);



CREATE POLICY "Roles are visible to everyone." ON "public"."roles" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Skill categories are visible to everyone." ON "public"."skill_categories" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Skill relations are visible to everyone." ON "public"."skill_relations" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Skill versions are visible to everyone." ON "public"."skill_versions" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Skills are visible to everyone." ON "public"."skills" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Tech stacks are visible to everyone." ON "public"."company_tech_stacks" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can select their user type" ON "public"."user_registrations" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



ALTER TABLE "public"."application_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."application_resumes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."applications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."companies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company_addresses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company_application_notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."company_tech_stacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hidden_jobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."industries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."interview_round_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."interview_rounds" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."interviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_seeker_application_notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_seeker_saved_searches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_seeker_skills" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_seekers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_skill_versions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."job_skills" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."jobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."saved_jobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."skill_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."skill_relations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."skill_versions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."skills" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_registrations" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "gis" TO "anon";
GRANT USAGE ON SCHEMA "gis" TO "authenticated";
GRANT USAGE ON SCHEMA "gis" TO "service_role";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."is_company"("_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_company"("_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_company"("_user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."is_job_seeker"("_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_job_seeker"("_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_job_seeker"("_user_id" "uuid") TO "service_role";


















GRANT ALL ON TABLE "public"."company_addresses" TO "anon";
GRANT ALL ON TABLE "public"."company_addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."company_addresses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."addresses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."application_events" TO "anon";
GRANT ALL ON TABLE "public"."application_events" TO "authenticated";
GRANT ALL ON TABLE "public"."application_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."application_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."application_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."application_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."application_resumes" TO "anon";
GRANT ALL ON TABLE "public"."application_resumes" TO "authenticated";
GRANT ALL ON TABLE "public"."application_resumes" TO "service_role";



GRANT ALL ON TABLE "public"."applications" TO "anon";
GRANT ALL ON TABLE "public"."applications" TO "authenticated";
GRANT ALL ON TABLE "public"."applications" TO "service_role";



GRANT ALL ON TABLE "public"."companies" TO "anon";
GRANT ALL ON TABLE "public"."companies" TO "authenticated";
GRANT ALL ON TABLE "public"."companies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company_application_notifications" TO "anon";
GRANT ALL ON TABLE "public"."company_application_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."company_application_notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."company_application_notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."company_application_notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."company_application_notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."company_tech_stacks" TO "anon";
GRANT ALL ON TABLE "public"."company_tech_stacks" TO "authenticated";
GRANT ALL ON TABLE "public"."company_tech_stacks" TO "service_role";



GRANT ALL ON TABLE "public"."hidden_jobs" TO "anon";
GRANT ALL ON TABLE "public"."hidden_jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."hidden_jobs" TO "service_role";



GRANT ALL ON TABLE "public"."industries" TO "anon";
GRANT ALL ON TABLE "public"."industries" TO "authenticated";
GRANT ALL ON TABLE "public"."industries" TO "service_role";



GRANT ALL ON SEQUENCE "public"."industries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."industries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."industries_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."interview_round_events" TO "anon";
GRANT ALL ON TABLE "public"."interview_round_events" TO "authenticated";
GRANT ALL ON TABLE "public"."interview_round_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."interview_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."interview_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."interview_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."interview_rounds" TO "anon";
GRANT ALL ON TABLE "public"."interview_rounds" TO "authenticated";
GRANT ALL ON TABLE "public"."interview_rounds" TO "service_role";



GRANT ALL ON SEQUENCE "public"."interview_rounds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."interview_rounds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."interview_rounds_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."interviews" TO "anon";
GRANT ALL ON TABLE "public"."interviews" TO "authenticated";
GRANT ALL ON TABLE "public"."interviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."interviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."interviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."interviews_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_applications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_applications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_applications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_roles" TO "anon";
GRANT ALL ON TABLE "public"."job_roles" TO "authenticated";
GRANT ALL ON TABLE "public"."job_roles" TO "service_role";



GRANT ALL ON TABLE "public"."job_seeker_application_notifications" TO "anon";
GRANT ALL ON TABLE "public"."job_seeker_application_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."job_seeker_application_notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_seeker_application_notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_seeker_application_notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_seeker_application_notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_seeker_saved_searches" TO "anon";
GRANT ALL ON TABLE "public"."job_seeker_saved_searches" TO "authenticated";
GRANT ALL ON TABLE "public"."job_seeker_saved_searches" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_seeker_saved_searches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_seeker_saved_searches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_seeker_saved_searches_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_seeker_skills" TO "anon";
GRANT ALL ON TABLE "public"."job_seeker_skills" TO "authenticated";
GRANT ALL ON TABLE "public"."job_seeker_skills" TO "service_role";



GRANT ALL ON TABLE "public"."job_seekers" TO "anon";
GRANT ALL ON TABLE "public"."job_seekers" TO "authenticated";
GRANT ALL ON TABLE "public"."job_seekers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job_seekers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job_seekers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job_seekers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_skill_versions" TO "anon";
GRANT ALL ON TABLE "public"."job_skill_versions" TO "authenticated";
GRANT ALL ON TABLE "public"."job_skill_versions" TO "service_role";



GRANT ALL ON TABLE "public"."job_skills" TO "anon";
GRANT ALL ON TABLE "public"."job_skills" TO "authenticated";
GRANT ALL ON TABLE "public"."job_skills" TO "service_role";



GRANT ALL ON TABLE "public"."jobs" TO "anon";
GRANT ALL ON TABLE "public"."jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."jobs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jobs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON TABLE "public"."saved_jobs" TO "anon";
GRANT ALL ON TABLE "public"."saved_jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."saved_jobs" TO "service_role";



GRANT ALL ON TABLE "public"."skill_categories" TO "anon";
GRANT ALL ON TABLE "public"."skill_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."skill_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."skill_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."skill_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."skill_categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."skill_relations" TO "anon";
GRANT ALL ON TABLE "public"."skill_relations" TO "authenticated";
GRANT ALL ON TABLE "public"."skill_relations" TO "service_role";



GRANT ALL ON TABLE "public"."skill_versions" TO "anon";
GRANT ALL ON TABLE "public"."skill_versions" TO "authenticated";
GRANT ALL ON TABLE "public"."skill_versions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."skill_versions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."skill_versions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."skill_versions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."skills" TO "anon";
GRANT ALL ON TABLE "public"."skills" TO "authenticated";
GRANT ALL ON TABLE "public"."skills" TO "service_role";



GRANT ALL ON SEQUENCE "public"."skills_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."skills_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."skills_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."titles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."titles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."titles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_registrations" TO "anon";
GRANT ALL ON TABLE "public"."user_registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."user_registrations" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON SEQUENCES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON FUNCTIONS TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "gis" GRANT ALL ON TABLES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































